### ISSUE TITLE
some question about using CMR-data test with this code

### ISSUE THREAD

**Issue by Cmnotjx** [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation#31]
When I tested CMR-dataset with SSL-ALPnet's code, several of the tested categories were all empty. I don't know if you have ever encountered this problem? Thank you for your answer!
![2023-03-10 08-28-14 的屏幕截图](https://user-images.githubusercontent.com/91420273/224193119-22383b92-adf6-43a7-aabc-2b346450fba6.png)

**Comment by Yffy123456** [comment]
Hello, could you share a copy of your CMR

**Comment by dengtianheibzzb** [comment]
Hello, I also encountered this problem. Can you explain how this problem was resolved?

**Comment by WangBingJian233** [comment]
Hello, could you please give us the CMR dataset？Thanks!

**Comment by WangBingJian233** [comment]
Hello, now the CMR dataset website has been closed, could you please give us the original data of the CMR dataset? I want to experiment with raw data sets in a super-pixel way. Thank you very much! Thank you very much! My email address is 1599025314@qq.com

**Comment by WangBingJian233** [comment]
> 您好，您能分享一份CMR的副本吗？

Have you found the CMR dataset yet? Could you please send me a copy if you find it? thank you.

**Comment by Yffy123456** [comment]
Hello, the author did not give me the relevant dataset




1967390362
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31)





  
您好，您能分享一份CMR的副本吗？
  
Have you found the CMR dataset yet? Could you please send me a copy if you find it? thank you.

**Comment by dengtianheibzzb** [comment]
I remember there was a paper called "Query Informed Feed Shot Medical Image Segmentation" that included this dataset in the open source code. You can look for it.




林深时见鹿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31)





 
Hello, could you please give us the CMR dataset？Thanks!

**Comment by WangBingJian233** [comment]
> 我记得有一篇论文叫做“Query Informed Feed Shot Medical Image Segmentation”，将这个数据集包含在开源代码中。你可以寻找它。 林深时见鹿 ***@***.*** &nbsp;
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation" ***@***.***&gt;; 发送时间:&nbsp;2024年2月13日(星期二) 晚上11:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31) Hello, could you please give us the CMR dataset？Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Thank you for your reply. You're talking about Q-Net, right? I paid attention to this paper, but its pre-processed data is hypervoxels (derived from AD-Net), not the hyperpixels used in this paper.

**Comment by Yffy123456** [comment]
Ok, thanks for your advice. Happy New Year.




1967390362
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月15日(星期四) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31)





  
我记得有一篇论文叫做“Query Informed Feed Shot Medical Image Segmentation”，将这个数据集包含在开源代码中。你可以寻找它。 林深时见鹿 @.*** &nbsp;
 ...
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation" @.&gt;; 发送时间:&nbsp;2024年2月13日(星期二) 晚上11:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31) Hello, could you please give us the CMR dataset？Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Thank you for your reply. You're talking about Q-Net, right? I paid attention to this paper, but its pre-processed data is hypervoxels (derived from AD-Net), not the hyperpixels used in this paper.

**Comment by 55227** [comment]
> > 我记得有一篇论文叫做“Query Informed Feed Shot Medical Image Segmentation”，将这个数据集包含在开源代码中。你可以寻找它。 林深时见鹿 _**@**_.***  
> > [...](#)
> > ------------------ 原始邮件 ------------------ 发件人: "cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation" _**@**_._**>; 发送时间: 2024年2月13日(星期二) 晚上11:24 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation] some question about using CMR-data test with this code (Issue #31) Hello, could you please give us the CMR dataset？Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> Thank you for your reply. You're talking about Q-Net, right? I paid attention to this paper, but its pre-processed data is hypervoxels (derived from AD-Net), not the hyperpixels used in this paper.

Have you solved this problem? I also want to find the hyperpixels used in this file, but I couldn't.
